const path = require('path');
const fs = require('fs');

const javaHome = path.join(process.env.USERPROFILE, 'AppData', 'Local', 'Temp', 'jdk17', 'jdk-17.0.13-lite');
process.env.JAVA_HOME = javaHome;
process.env.PATH = `${javaHome}\\bin;${process.env.PATH}`;

const {
  TwaManifest,
  TwaGenerator,
  Config,
  GradleWrapper,
  AndroidSdkTools,
  JdkHelper,
  JarSigner
} = require('@bubblewrap/core');

const ROOT = path.join(__dirname, '..');
const MANIFEST_PATH = path.join(ROOT, 'twa-manifest.json');
const BUILD_DIR = path.join(ROOT, 'app');
const OUTPUT_APK = path.join(ROOT, 'VenezuelaCrisis.apk');

async function main() {
  console.log('=== Venezuela Crisis - APK Builder ===\n');

  // Load manifest
  const manifest = TwaManifest.fromFile(MANIFEST_PATH);
  console.log('✓ Manifest loaded:', manifest.name);

  // Configure JDK
  JdkHelper.setJdkPath(javaHome);
  console.log('✓ JDK configured');

  // Set up Android SDK
  const sdkDir = path.join(process.env.USERPROFILE, '.bubblewrap', 'android-sdk');
  const config = new Config({ jdkPath: javaHome, androidSdkPath: sdkDir });
  console.log('✓ Config created');

  // Check if we need to install the Android SDK
  if (!fs.existsSync(sdkDir) || !fs.existsSync(path.join(sdkDir, 'platforms'))) {
    console.log('\nDownloading Android SDK...');
    fs.mkdirSync(sdkDir, { recursive: true });
    process.stdout.write('  This may take a few minutes...\n');
    
    const sdkTools = new AndroidSdkTools(config, new (require('@bubblewrap/core').ConsoleLog)());
    await sdkTools.installSdk(sdkDir);
    console.log('✓ Android SDK installed');
  } else {
    console.log('✓ Android SDK found');
  }

  // Build
  console.log('\nBuilding APK...');
  const generator = new TwaGenerator(config, new (require('@bubblewrap/core').ConsoleLog)());

  await generator.createProject(BUILD_DIR, manifest);
  console.log('✓ Project created');
  
  await generator.buildApp(BUILD_DIR, path.join(ROOT, 'app-release.apk'));
  console.log('✓ APK built');

  // Sign with debug key (auto-generated by Gradle)
  const apkPath = path.join(BUILD_DIR, 'app', 'build', 'outputs', 'apk', 'release', 'app-release-unsigned.apk');
  const signedApk = path.join(BUILD_DIR, 'app', 'build', 'outputs', 'apk', 'release', 'app-release-signed.apk');
  
  if (fs.existsSync(apkPath)) {
    const signer = new JarSigner(javaHome);
    await signer.signApk(apkPath, signedApk, manifest);
    fs.copyFileSync(signedApk, OUTPUT_APK);
    fs.copyFileSync(apkPath, path.join(ROOT, 'VenezuelaCrisis-unsigned.apk'));
    console.log(`\n✓ APK final: ${OUTPUT_APK}`);
    console.log(`  Tamaño: ${(fs.statSync(OUTPUT_APK).size / 1e6).toFixed(1)} MB`);
  } else {
    // Try finding the APK elsewhere
    const findApk = (dir) => {
      if (!fs.existsSync(dir)) return null;
      for (const f of fs.readdirSync(dir, { recursive: true })) {
        if (f.endsWith('.apk')) return path.join(dir, f);
      }
      return null;
    };
    const found = findApk(path.join(BUILD_DIR));
    if (found) {
      fs.copyFileSync(found, OUTPUT_APK);
      console.log(`\n✓ APK encontrado: ${found}`);
      console.log(`  Copiado a: ${OUTPUT_APK}`);
    } else {
      console.log('\n✗ No se encontró el APK. Revisá la carpeta app/');
    }
  }
}

main().catch(err => {
  console.error('\n✗ Error:', err.message);
  process.exit(1);
});
